database:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5438/habit_tracker
  username: vladimir
  password: qwerty
liquibase:
  changelogFilePath: db.changelog/changelog.xml
