version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: habit_tracker
    environment:
      POSTGRES_USER: vladimir
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: habit_tracker
    ports:
      - "5438:5432"